In [4]:
import tensorflow as tf
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import cifar10
import numpy as np

physical_devices=tf.config.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(physical_devices[0],True)

In [5]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [6]:
x=tf.constant(4,shape=(3,3))
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])>

In [7]:
tf.ones((3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [8]:
tf.zeros([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
tf.random.uniform((1,3),0,1)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.7298571 , 0.801092  , 0.64059293]], dtype=float32)>

In [11]:
x = tf.random.normal((3,3),0,1)

In [12]:
y=tf.cast(x,dtype=tf.float64)
y

<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[-0.56514019, -1.57580554, -1.03138876],
       [ 0.87250131, -1.9267801 ,  0.85918361],
       [ 0.37921253,  1.80367064, -0.94560587]])>

## calculate

In [13]:
a=tf.constant([1,2,3])
b=tf.constant([4,5,6])
a+b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 7, 9])>

In [14]:
a-b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-3, -3, -3])>

In [15]:
a/b

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.25, 0.4 , 0.5 ])>

In [16]:
a*b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 4, 10, 18])>

In [17]:
c=tf.tensordot(a,b,axes=1)
c=tf.reduce_sum(a*b,0)
c

<tf.Tensor: shape=(), dtype=int32, numpy=32>

In [20]:
# x=tf.constant((2,2),4)
# y=tf.constant((2,2),2)
x=tf.random.normal((100,100))
y=tf.random.normal((100,100))
tf.matmul(x,y)

<tf.Tensor: shape=(100, 100), dtype=float32, numpy=
array([[  3.9121017 ,  10.93853   ,  -2.2238023 , ..., -12.746608  ,
          7.7449903 ,  -8.099891  ],
       [ -2.291286  ,  -0.07909968, -21.145823  , ...,  11.783613  ,
         15.0866    ,  -3.3321948 ],
       [ -7.565598  , -11.66715   , -16.815098  , ...,  -2.5744328 ,
         10.189963  ,   9.019874  ],
       ...,
       [ 26.331348  ,  -7.0635023 ,   5.031777  , ...,  13.761663  ,
         -8.5909815 ,   2.1942902 ],
       [-10.386876  , -13.864874  ,   4.078139  , ...,  -0.63627505,
        -12.724531  ,  -1.8129038 ],
       [  2.0940118 ,  15.452338  ,  -1.2669147 , ...,  -5.51189   ,
          5.060686  ,  -2.9707294 ]], dtype=float32)>

In [1]:
_

''