In [257]:
import numpy as np

c=np.array([6,-2,3,0,0],dtype=np.float)
A=np.array([[2,-1,2,1,0],[1,0,4,0,1]],dtype=np.float)
b=np.array([[2],[4]],dtype=np.float)
B=np.array([4,5])
o=np.array([6,-2,3,0,0],dtype=np.float)
cb=np.array([0,0],dtype=np.float)

flag=True
while flag==True:
    j1=np.where(o==max(o))
    j1=j1[0]
    z0=z1=[[100.]]
    if(A[0,j1]>0):
        z0=b[0,0]/A[0,j1]
    if(A[1,j1]>0):
        z1=b[1,0]/A[1,j1]
    if z1<z0:i=1
    if z1>z0:i=0
    i1=A[i,j1]
    for x in range(5):
        A[i,x]=A[i,x]/i1
    b[i,0]=b[i,0]/i1
    m=A[1-i,j1]
    for x in range(5):
        A[1-i,x]=A[1-i,x]-m*A[i,x]
    b[1-i,0]=b[1-i,0]-b[i,0]*m
    cb[i]=c[j1]
    B[i]=j1
    for x in range(5):
        o[x]=c[x]-cb[0]*A[0,x]-cb[1]*A[1,x]
    flag=False
    for x in o:
         if x>0:
            flag=True
z=0
v=np.array([0,0,0,0,0])
for i in range(2):
    x=B[i]
    v[x]=b[i]
    z=z+c[x]*b[i]
print('最优解为',v,'最优目标函数值为',z) 

最优解为 [4 6 0 0 0] 最优目标函数值为 [12.]


In [254]:
z=0
print(c,b)
v=np.array([0,0,0,0,0])
for i in range(2):
    x=B[i]
    v[x]=b[i]
    print(x)
    z=z+c[x]*b[i]
print('最优解为',v,'最优目标函数值为',z)    

[ 6. -2.  3.  0.  0.] [[4.]
 [6.]]
0
1
[4 6 0 0 0] [12.]


In [239]:
B[0]

0.0

In [224]:
flag=True
while flag==True:
    j1=np.where(o==max(o))
    j1=j1[0]
    print(1,j1)
    z0=z1=[[100.]]
    if(A[0,j1]>0):
        z0=b[0,0]/A[0,j1]
    if(A[1,j1]>0):
        z1=b[1,0]/A[1,j1]
    if z1<z0:i=1
    if z1>z0:i=0
    i1=A[i,j1]
    print(2,i1)
    for x in range(5):
        A[i,x]=A[i,x]/i1
    b[i,0]=b[i,0]/i1
    m=A[1-i,j1]
    for x in range(5):
        A[1-i,x]=A[1-i,x]-m*A[i,x]
    b[1-i,0]=b[1-i,0]-b[i,0]*m
    cb[i]=c[j1]
    print(c,c[j1])
    print(3,o)
    for x in range(5):
        o[x]=c[x]-cb[0]*A[0,x]-cb[1]*A[1,x]
    print(4,b)
    print(5,cb)
    print(6,A)
    print(7,o)
    flag=False
    for x in o:
         if x>0:
            flag=True    

1 [0]
2 [2.]
[ 6. -2.  3.  0.  0.] [6.]
3 [ 6. -2.  3.  0.  0.]
4 [[1.]
 [3.]]
5 [6. 0.]
6 [[ 1.  -0.5  1.   0.5  0. ]
 [ 0.   0.5  3.  -0.5  1. ]]
7 [ 0.  1. -3. -3.  0.]
1 [1]
2 [0.5]
[ 6. -2.  3.  0.  0.] [-2.]
3 [ 0.  1. -3. -3.  0.]
4 [[4.]
 [6.]]
5 [ 6. -2.]
6 [[ 1.  0.  4.  0.  1.]
 [ 0.  1.  6. -1.  2.]]
7 [ 0.  0. -9. -2. -2.]
1 [0 1]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [16]:
A1 = np.concatenate((b, A),axis=1)
print(A1)

[[ 2  2 -1  2  1  0]
 [ 4  1  0  4  0  1]]


In [107]:
x=max(o)
print(x)

1.0


In [94]:
i1=A[i,j1]
print(i1)
for x in range(5):
    A[i,x]=A[i,x]/i1
b[i,0]=b[i,0]/i1
print(b)
m=A[1-i,j1]
for x in range(5):
    A[1-i,x]=A[1-i,x]-m*A[i,x]
b[1-i,0]=b[1-i,0]-b[i,0]*m
m=o[j1]
for x in range(5):
    o[x]=o[x]-m*A[i,x]
print(b)
print(A)
print(o)
for x in o:
     if x>0:
        flag=true

[[1.]]
[[1.]
 [3.]]
[[1.]
 [3.]]
[[ 1.  -0.5  1.   0.5  0. ]
 [ 0.   0.5  3.  -0.5  1. ]]
[ 0.  1. -9. -3.  0.]


In [101]:
    j1=np.where(max(o))
    z0=z1=0
    if(z0>0):
        z0=b[0,0]/A[0,j1]
    if(z1>0):
        z1=b[1,0]/A[1,j1]
    if z1>=z0:i=0 
    else:i=1
    i1=A[i,j1]
    print(i1)
    for x in range(5):
        A[i,x]=A[i,x]/i1
    b[i,0]=b[i,0]/i1
    m=A[1-i,j1]
    for x in range(5):
        A[1-i,x]=A[1-i,x]-m*A[i,x]
    b[1-i,0]=b[1-i,0]-b[i,0]*m
    m=o[j1]
    for x in range(5):
        o[x]=o[x]-m*A[i,x]
    print(b)
    print(A)
    print(o)

[[1.]]
[[1.]
 [3.]]
[[ 1.  -0.5  1.   0.5  0. ]
 [ 0.   0.5  3.  -0.5  1. ]]
[ 0.  1. -9. -3.  0.]


In [59]:
type(j)

int